name: plant-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - addict=2.4.0
  - blas=1.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cairo=1.16.0
  - certifi=2021.5.30
  - cfitsio=3.470
  - colorama=0.4.4
  - curl=7.78.0
  - cycler=0.10.0
  - draco=1.4.1
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.1
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.21.0
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - intel-openmp=2021.3.0
  - jbig=2.1
  - jpeg=9d
  - json-c=0.15
  - jsoncpp=1.9.4
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - laszip=3.4.3
  - laz-perf=2.0.0
  - lcms2=2.12
  - lerc=2.2.1
  - libcurl=7.78.0
  - libcxx=12.0.1
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgdal=3.3.1
  - libgfortran5=9.3.0
  - libglib=2.68.3
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzip=1.8.0
  - llvm-openmp=10.0.0
  - lz4-c=1.9.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.2
  - nitro=2.7.dev6
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.3.1
  - pcre=8.45
  - pdal=2.3.0
  - pillow=8.3.1
  - pip=21.2.2
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pkgconfig=1.5.4
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.3
  - proj=8.0.1
  - pyparsing=2.4.7
  - python=3.8.11
  - python-dateutil=2.8.2
  - python-pdal=2.4.2
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tiledb=2.3.2
  - tk=8.6.10
  - tornado=6.1
  - tqdm=4.62.0
  - tzcode=2021a
  - tzdata=2021a
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - appnope==0.1.2
    - backcall==0.2.0
    - debugpy==1.4.1
    - decorator==5.0.9
    - ipykernel==6.0.3
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.0.1
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - laspy==2.0.2
    - matplotlib-inline==0.1.2
    - open3d==0.13.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plyfile==0.7.4
    - prompt-toolkit==3.0.19
    - ptyprocess==0.7.0
    - pygments==2.9.0
    - pyzmq==22.2.0
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - threadpoolctl==2.2.0
    - traitlets==5.0.5
    - wcwidth==0.2.5
    - libgfortran==5.0.0